# Bioconductor
_29 de enero de 2025_  

Bioconductor se ocupa de desarrollar paquetes de R que son útiles para 
el análisis de datos en bioinformática.  

Dentro de la página web de Bioconductor pueden encontrarse los paquetes 
clasificados según su función y utilidad. Una ventaja de Bioconductor 
sobre los paquetes de CRAN es que se encuentran mejor documentados y 
son revisados de una forma más periódica y constante.  

Algunos comandos importantes son:  
- Instalar paquetes:  
```{r, eval = FALSE}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DOSE")
```  
- `browseVignettes("iCARE")`: Acceder a documentación del paquete.  

Es importante explorar los didtintos paquetes disponibles, pues siempre 
se puede encontrar algo nuevo que resulte útil para nuestras necesidades. 
Como algo opcional, es aconsejable crear un blog personal con los 
paquetes que más resulten de nuestro agrado.  

Con el fin de mantenerse actualizado, se recomienda explorar la página 
de Bioconductor, donde se publican videos explicando paquetes y funciones, 
así como avisos de congresos, talleres y eventos futuros. Además, hay un 
Slack disponible para estar en contacto constante con colaboradores de 
Bioconductor.  
